server {
  listen 80;
  server_name _;

  access_log /var/log/nginx/access-file.log;
  error_log  /var/log/nginx/error-file.log warn;

  location = / {
    return 200 "ok\n";
  }

  location = /error {
    return 500 "forced error\n";
  }

  location = /notfound {
    return 404 "forced 404\n";
  }

  location = /nginx_status {
    stub_status;
    access_log off;
  }
}
