name: meeting-02-homework-traces-to-red

services:
  grafana:
    image: grafana/grafana:12.3.1
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
    depends_on:
      - mimir
      - tempo

  mimir:
    image: grafana/mimir:2.17.4
    command: ["-ingester.native-histograms-ingestion-enabled=true", "-config.file=/etc/mimir.yaml"]
    ports:
      - "9009:9009"
    volumes:
      - "./mimir/mimir.yaml:/etc/mimir.yaml"

  tempo:
    image: grafana/tempo:2.9.0
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"
      - "4319:4317"
    volumes:
      - "./tempo/tempo.yaml:/etc/tempo.yaml"

  alloy:
    image: grafana/alloy:v1.12.1
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "/etc/alloy/config.alloy"
    ]
    ports:
      - "12347:12345"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - "./alloy/config.alloy:/etc/alloy/config.alloy"
      - "./alloy/endpoints.json:/etc/alloy/endpoints.json"
    depends_on:
      - mimir
      - tempo

  tracegen:
    build:
      context: ./tracegen
    restart: unless-stopped
    environment:
      - OTLP_ENDPOINT=alloy:4317
      - OTEL_SERVICE_NAME=checkout-simulator
    depends_on:
      - alloy
